### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by SwatiSavarna**
typo error at line no 24

### CODE REVIEW

**Comment by SwatiSavarna** [comment]
typing errors

**Comment by SwatiSavarna** [comment]
Hello
I am a GSSoC'24 contributor and looking forward to work on this
@juhinagpure  eagerly waiting for your reply

**Review by juhinagpure — APPROVED** [review]

**Comment by SwatiSavarna** [comment]
please add gssoc level1 labels for recognizing our contributions

**Comment by SwatiSavarna** [comment]
also I would like to contribute for making the hamburger menu responsive.....please assign this task to me...i would like to work on it with the best of my experience

**Pull request merged**
